/* Generated By:JavaCC: Do not edit this line. AdderConstants.java */
public interface AdderConstants {

  int EOF = 0;
  int PLUS = 5;
  int NUMBER = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"+\"",
    "<NUMBER>",
  };

}
