/* Generated By:JavaCC: Do not edit this line. MainConstants.java */
public interface MainConstants {

  int EOF = 0;
  int OP = 5;
  int ROP = 6;
  int ID = 7;
  int NUM = 8;
  int EMPTY = 9;
  int OPEN_PAR = 10;
  int CLOSE_PAR = 11;
  int LETTER = 12;
  int SMALL_LETTER = 13;
  int DIGIT = 14;
  int LEADING_DIGIT = 15;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<OP>",
    "<ROP>",
    "<ID>",
    "<NUM>",
    "<EMPTY>",
    "\"(\"",
    "\")\"",
    "<LETTER>",
    "<SMALL_LETTER>",
    "<DIGIT>",
    "<LEADING_DIGIT>",
  };

}
